#!/usr/bin/env bash
#
# Game mode visual strip.
#
# Hyprland could be reconfigured live, so this used to snapshot every decoration
# value, push zeros over the top through `hyprctl eval`, and push the snapshot
# back on the way out — with the snapshot on disk so a pill restart mid-game
# could still undo it.
#
# niri has no live-eval, but it watches its config and reloads on change, which
# turns out to be the simpler mechanism. Rather than mutating state and
# remembering how to put it back, this writes an override layer: `on` fills the
# file, `off` empties it. Coming back is the base config simply being unopposed
# again, so there is no snapshot to keep, nothing to get out of sync, and a pill
# that dies mid-game leaves a file you can delete by hand.
#
# Opt in with one line at the END of ~/.config/niri/config.kdl, after your own
# layout — includes override what came before them, so the position matters:
#
#     include optional=true "ricelin-gamemode.kdl"
#
# Without that line this writes a file nothing reads, and game mode still quiets
# notifications, pauses the visualizer, holds the session awake and slims the
# bar. Only the compositor decoration stays put.
#
set -euo pipefail

conf="${XDG_CONFIG_HOME:-$HOME/.config}/niri"
overlay="$conf/ricelin-gamemode.kdl"

# Rename rather than write in place, in both directions: niri watches this path,
# and it should never observe a half-written file — that is a parse error, not a
# config, and it would take the whole config down with it.
publish() {
	mkdir -p "$conf"
	cat >"$overlay.tmp"
	mv -f "$overlay.tmp" "$overlay"
}

case "${1:-}" in
on)
	publish <<'KDL'
// Generated by Ricelin's game mode. Emptied on the way out; safe to delete.
layout {
    gaps 0
    focus-ring {
        off
    }
    border {
        off
    }
    shadow {
        off
    }
}

animations {
    off
}
KDL
	;;
off)
	publish <<'KDL'
// Generated by Ricelin's game mode. Empty means game mode is off.
KDL
	;;
*)
	echo "usage: gamemode.sh on|off" >&2
	exit 1
	;;
esac
